name: Docker CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * 1'

env:
  docker-repo: loyayz

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:

    name: Build docker image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: postgres15
        run: |
          cd postgres15
          docker build -t ${{ env.docker-repo }}/postgres15:latest .
          cd ..

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{  (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request')  }}
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push docker image to Docker Hub
        if: ${{  (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request')  }}
        run: docker push ${{ env.docker-repo }}/postgres15:latest
